// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: pb_stats/stat_notify.proto

package pb_stats

import (
	pb_pub "github.com/leallee00/pb/pb_pub"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatisticNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PbCommData *pb_pub.PBCommData `protobuf:"bytes,1,opt,name=pbCommData,proto3" json:"pbCommData,omitempty"`
	PbName     string             `protobuf:"bytes,2,opt,name=pbName,proto3" json:"pbName,omitempty"`
	PbData     []byte             `protobuf:"bytes,3,opt,name=pbData,proto3" json:"pbData,omitempty"`
}

func (x *StatisticNotify) Reset() {
	*x = StatisticNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stats_stat_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticNotify) ProtoMessage() {}

func (x *StatisticNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stats_stat_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticNotify.ProtoReflect.Descriptor instead.
func (*StatisticNotify) Descriptor() ([]byte, []int) {
	return file_pb_stats_stat_notify_proto_rawDescGZIP(), []int{0}
}

func (x *StatisticNotify) GetPbCommData() *pb_pub.PBCommData {
	if x != nil {
		return x.PbCommData
	}
	return nil
}

func (x *StatisticNotify) GetPbName() string {
	if x != nil {
		return x.PbName
	}
	return ""
}

func (x *StatisticNotify) GetPbData() []byte {
	if x != nil {
		return x.PbData
	}
	return nil
}

// 邀请状态变更
type InvitationStatusChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallerId   int64 `protobuf:"varint,1,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId   int64 `protobuf:"varint,2,opt,name=calleeId,proto3" json:"calleeId,omitempty"`
	InviteTime int64 `protobuf:"varint,3,opt,name=inviteTime,proto3" json:"inviteTime,omitempty"`
	Interval   int64 `protobuf:"varint,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Price      int64 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Status     int32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *InvitationStatusChanged) Reset() {
	*x = InvitationStatusChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stats_stat_notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvitationStatusChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitationStatusChanged) ProtoMessage() {}

func (x *InvitationStatusChanged) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stats_stat_notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitationStatusChanged.ProtoReflect.Descriptor instead.
func (*InvitationStatusChanged) Descriptor() ([]byte, []int) {
	return file_pb_stats_stat_notify_proto_rawDescGZIP(), []int{1}
}

func (x *InvitationStatusChanged) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *InvitationStatusChanged) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

func (x *InvitationStatusChanged) GetInviteTime() int64 {
	if x != nil {
		return x.InviteTime
	}
	return 0
}

func (x *InvitationStatusChanged) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *InvitationStatusChanged) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *InvitationStatusChanged) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// chatroom 关闭
type ChatRoomClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	CallerId  int64 `protobuf:"varint,2,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId  int64 `protobuf:"varint,3,opt,name=calleeId,proto3" json:"calleeId,omitempty"`
	StartTime int64 `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	CloseTime int64 `protobuf:"varint,5,opt,name=closeTime,proto3" json:"closeTime,omitempty"`
	Duration  int64 `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Interval  int64 `protobuf:"varint,7,opt,name=interval,proto3" json:"interval,omitempty"`
	Price     int64 `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	Round     int64 `protobuf:"varint,9,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *ChatRoomClosed) Reset() {
	*x = ChatRoomClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stats_stat_notify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRoomClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomClosed) ProtoMessage() {}

func (x *ChatRoomClosed) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stats_stat_notify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomClosed.ProtoReflect.Descriptor instead.
func (*ChatRoomClosed) Descriptor() ([]byte, []int) {
	return file_pb_stats_stat_notify_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRoomClosed) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ChatRoomClosed) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ChatRoomClosed) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

func (x *ChatRoomClosed) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ChatRoomClosed) GetCloseTime() int64 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

func (x *ChatRoomClosed) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ChatRoomClosed) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *ChatRoomClosed) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ChatRoomClosed) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

// videoroom 关闭
type VideoRoomClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`       // 用户Id
	RoomId    int64 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`       // 房间Id
	EnterTime int64 `protobuf:"varint,3,opt,name=EnterTime,proto3" json:"EnterTime,omitempty"` // 进入时刻(ts 精度秒)
	ExitTime  int64 `protobuf:"varint,4,opt,name=ExitTime,proto3" json:"ExitTime,omitempty"`   // 离开时刻(ts 精度秒)
	WatchTime int64 `protobuf:"varint,5,opt,name=WatchTime,proto3" json:"WatchTime,omitempty"` // 观播▶️时长
}

func (x *VideoRoomClosed) Reset() {
	*x = VideoRoomClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stats_stat_notify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoRoomClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRoomClosed) ProtoMessage() {}

func (x *VideoRoomClosed) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stats_stat_notify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRoomClosed.ProtoReflect.Descriptor instead.
func (*VideoRoomClosed) Descriptor() ([]byte, []int) {
	return file_pb_stats_stat_notify_proto_rawDescGZIP(), []int{3}
}

func (x *VideoRoomClosed) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VideoRoomClosed) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *VideoRoomClosed) GetEnterTime() int64 {
	if x != nil {
		return x.EnterTime
	}
	return 0
}

func (x *VideoRoomClosed) GetExitTime() int64 {
	if x != nil {
		return x.ExitTime
	}
	return 0
}

func (x *VideoRoomClosed) GetWatchTime() int64 {
	if x != nil {
		return x.WatchTime
	}
	return 0
}

var File_pb_stats_stat_notify_proto protoreflect.FileDescriptor

var file_pb_stats_stat_notify_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x62, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x5f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x62,
	0x5f, 0x70, 0x75, 0x62, 0x1a, 0x11, 0x70, 0x62, 0x5f, 0x70, 0x75, 0x62, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x32, 0x0a, 0x0a, 0x70, 0x62,
	0x43, 0x6f, 0x6d, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x62, 0x5f, 0x70, 0x75, 0x62, 0x2e, 0x50, 0x42, 0x43, 0x6f, 0x6d, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x0a, 0x70, 0x62, 0x43, 0x6f, 0x6d, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x62, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x62, 0x44, 0x61, 0x74, 0x61, 0x22, 0xbb,
	0x01, 0x0a, 0x17, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x80, 0x02, 0x0a,
	0x0e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22,
	0x99, 0x01, 0x0a, 0x0f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x45, 0x78, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x57, 0x61, 0x74, 0x63, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x57, 0x61, 0x74, 0x63, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x22, 0x5a, 0x20, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x61, 0x6c, 0x6c, 0x65,
	0x65, 0x30, 0x30, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_stats_stat_notify_proto_rawDescOnce sync.Once
	file_pb_stats_stat_notify_proto_rawDescData = file_pb_stats_stat_notify_proto_rawDesc
)

func file_pb_stats_stat_notify_proto_rawDescGZIP() []byte {
	file_pb_stats_stat_notify_proto_rawDescOnce.Do(func() {
		file_pb_stats_stat_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_stats_stat_notify_proto_rawDescData)
	})
	return file_pb_stats_stat_notify_proto_rawDescData
}

var file_pb_stats_stat_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_stats_stat_notify_proto_goTypes = []interface{}{
	(*StatisticNotify)(nil),         // 0: pb_pub.StatisticNotify
	(*InvitationStatusChanged)(nil), // 1: pb_pub.InvitationStatusChanged
	(*ChatRoomClosed)(nil),          // 2: pb_pub.ChatRoomClosed
	(*VideoRoomClosed)(nil),         // 3: pb_pub.VideoRoomClosed
	(*pb_pub.PBCommData)(nil),       // 4: pb_pub.PBCommData
}
var file_pb_stats_stat_notify_proto_depIdxs = []int32{
	4, // 0: pb_pub.StatisticNotify.pbCommData:type_name -> pb_pub.PBCommData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_stats_stat_notify_proto_init() }
func file_pb_stats_stat_notify_proto_init() {
	if File_pb_stats_stat_notify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_stats_stat_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stats_stat_notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvitationStatusChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stats_stat_notify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRoomClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stats_stat_notify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoRoomClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_stats_stat_notify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_stats_stat_notify_proto_goTypes,
		DependencyIndexes: file_pb_stats_stat_notify_proto_depIdxs,
		MessageInfos:      file_pb_stats_stat_notify_proto_msgTypes,
	}.Build()
	File_pb_stats_stat_notify_proto = out.File
	file_pb_stats_stat_notify_proto_rawDesc = nil
	file_pb_stats_stat_notify_proto_goTypes = nil
	file_pb_stats_stat_notify_proto_depIdxs = nil
}
