// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: pb_msg/live_room/secret_room.proto

package live_room

import (
	pb_pub "github.com/leallee00/pb/pb_pub"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CHAT_ANSWER int32

const (
	CHAT_ANSWER_REFUSE CHAT_ANSWER = 0
	CHAT_ANSWER_AGREE  CHAT_ANSWER = 1
)

// Enum value maps for CHAT_ANSWER.
var (
	CHAT_ANSWER_name = map[int32]string{
		0: "REFUSE",
		1: "AGREE",
	}
	CHAT_ANSWER_value = map[string]int32{
		"REFUSE": 0,
		"AGREE":  1,
	}
)

func (x CHAT_ANSWER) Enum() *CHAT_ANSWER {
	p := new(CHAT_ANSWER)
	*p = x
	return p
}

func (x CHAT_ANSWER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CHAT_ANSWER) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_msg_live_room_secret_room_proto_enumTypes[0].Descriptor()
}

func (CHAT_ANSWER) Type() protoreflect.EnumType {
	return &file_pb_msg_live_room_secret_room_proto_enumTypes[0]
}

func (x CHAT_ANSWER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CHAT_ANSWER.Descriptor instead.
func (CHAT_ANSWER) EnumDescriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{0}
}

type CHAT_CLOSE_TYPE int32

const (
	CHAT_CLOSE_TYPE_TIMEOUT CHAT_CLOSE_TYPE = 0 // 因为时间到结束
	CHAT_CLOSE_TYPE_MANUAL  CHAT_CLOSE_TYPE = 1 // 邀请房主动关闭
	CHAT_CLOSE_TYPE_BY_HOST CHAT_CLOSE_TYPE = 2 // 由于派对房关闭导致的小黑屋关闭
)

// Enum value maps for CHAT_CLOSE_TYPE.
var (
	CHAT_CLOSE_TYPE_name = map[int32]string{
		0: "TIMEOUT",
		1: "MANUAL",
		2: "BY_HOST",
	}
	CHAT_CLOSE_TYPE_value = map[string]int32{
		"TIMEOUT": 0,
		"MANUAL":  1,
		"BY_HOST": 2,
	}
)

func (x CHAT_CLOSE_TYPE) Enum() *CHAT_CLOSE_TYPE {
	p := new(CHAT_CLOSE_TYPE)
	*p = x
	return p
}

func (x CHAT_CLOSE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CHAT_CLOSE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_msg_live_room_secret_room_proto_enumTypes[1].Descriptor()
}

func (CHAT_CLOSE_TYPE) Type() protoreflect.EnumType {
	return &file_pb_msg_live_room_secret_room_proto_enumTypes[1]
}

func (x CHAT_CLOSE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CHAT_CLOSE_TYPE.Descriptor instead.
func (CHAT_CLOSE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{1}
}

// 聊天室用户
type Chatter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserProp   *UserProp `protobuf:"bytes,1,opt,name=userProp,proto3" json:"userProp,omitempty"`
	VideoState int32     `protobuf:"varint,4,opt,name=videoState,proto3" json:"videoState,omitempty"` // 视频状态
	AudioState int32     `protobuf:"varint,5,opt,name=audioState,proto3" json:"audioState,omitempty"` // 音频状态
	LeaveState int64     `protobuf:"varint,6,opt,name=leaveState,proto3" json:"leaveState,omitempty"` // 暂离状态
}

func (x *Chatter) Reset() {
	*x = Chatter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chatter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chatter) ProtoMessage() {}

func (x *Chatter) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chatter.ProtoReflect.Descriptor instead.
func (*Chatter) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{0}
}

func (x *Chatter) GetUserProp() *UserProp {
	if x != nil {
		return x.UserProp
	}
	return nil
}

func (x *Chatter) GetVideoState() int32 {
	if x != nil {
		return x.VideoState
	}
	return 0
}

func (x *Chatter) GetAudioState() int32 {
	if x != nil {
		return x.AudioState
	}
	return 0
}

func (x *Chatter) GetLeaveState() int64 {
	if x != nil {
		return x.LeaveState
	}
	return 0
}

// 聊天室结构
type ChatRoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caller      *Chatter `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`            // 邀请方
	Callee      *Chatter `protobuf:"bytes,2,opt,name=callee,proto3" json:"callee,omitempty"`            // 被邀请方
	Interval    int64    `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`       // 计费间隔
	Price       int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`             // 单位间隔话费
	Deadline    int64    `protobuf:"varint,5,opt,name=deadline,proto3" json:"deadline,omitempty"`       // 结束时间点
	AutoRenewal bool     `protobuf:"varint,6,opt,name=autoRenewal,proto3" json:"autoRenewal,omitempty"` // 自动续费状态
	OneMore     bool     `protobuf:"varint,7,opt,name=oneMore,proto3" json:"oneMore,omitempty"`         // 再聊一场状态
	ChannelId   string   `protobuf:"bytes,8,opt,name=channelId,proto3" json:"channelId,omitempty"`      // 频道号
}

func (x *ChatRoomInfo) Reset() {
	*x = ChatRoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomInfo) ProtoMessage() {}

func (x *ChatRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomInfo.ProtoReflect.Descriptor instead.
func (*ChatRoomInfo) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRoomInfo) GetCaller() *Chatter {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *ChatRoomInfo) GetCallee() *Chatter {
	if x != nil {
		return x.Callee
	}
	return nil
}

func (x *ChatRoomInfo) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *ChatRoomInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ChatRoomInfo) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *ChatRoomInfo) GetAutoRenewal() bool {
	if x != nil {
		return x.AutoRenewal
	}
	return false
}

func (x *ChatRoomInfo) GetOneMore() bool {
	if x != nil {
		return x.OneMore
	}
	return false
}

func (x *ChatRoomInfo) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// 设置连麦付费规则,持久化到redis, 转发到全房间
type UpdateChatPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interval int64 `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Price    int64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *UpdateChatPrice) Reset() {
	*x = UpdateChatPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChatPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatPrice) ProtoMessage() {}

func (x *UpdateChatPrice) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatPrice.ProtoReflect.Descriptor instead.
func (*UpdateChatPrice) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateChatPrice) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *UpdateChatPrice) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// 用户申请
type ChatApplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CalleeId          int64  `protobuf:"varint,1,opt,name=calleeId,proto3" json:"calleeId,omitempty"` // 必填
	CallerId          int64  `protobuf:"varint,2,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CallerName        string `protobuf:"bytes,3,opt,name=callerName,proto3" json:"callerName,omitempty"`
	CallerHeaderImage string `protobuf:"bytes,4,opt,name=callerHeaderImage,proto3" json:"callerHeaderImage,omitempty"`
	InviteTime        int64  `protobuf:"varint,5,opt,name=inviteTime,proto3" json:"inviteTime,omitempty"`
}

func (x *ChatApplyReq) Reset() {
	*x = ChatApplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatApplyReq) ProtoMessage() {}

func (x *ChatApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatApplyReq.ProtoReflect.Descriptor instead.
func (*ChatApplyReq) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{3}
}

func (x *ChatApplyReq) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

func (x *ChatApplyReq) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ChatApplyReq) GetCallerName() string {
	if x != nil {
		return x.CallerName
	}
	return ""
}

func (x *ChatApplyReq) GetCallerHeaderImage() string {
	if x != nil {
		return x.CallerHeaderImage
	}
	return ""
}

func (x *ChatApplyReq) GetInviteTime() int64 {
	if x != nil {
		return x.InviteTime
	}
	return 0
}

type ChatApplyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode  pb_pub.ErrCode `protobuf:"varint,1,opt,name=errCode,proto3,enum=pb_pub.ErrCode" json:"errCode,omitempty"`
	ErrDesc  string         `protobuf:"bytes,2,opt,name=errDesc,proto3" json:"errDesc,omitempty"`
	CallerId int64          `protobuf:"varint,3,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId int64          `protobuf:"varint,4,opt,name=calleeId,proto3" json:"calleeId,omitempty"` // 必填
}

func (x *ChatApplyRsp) Reset() {
	*x = ChatApplyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatApplyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatApplyRsp) ProtoMessage() {}

func (x *ChatApplyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatApplyRsp.ProtoReflect.Descriptor instead.
func (*ChatApplyRsp) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{4}
}

func (x *ChatApplyRsp) GetErrCode() pb_pub.ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_pub.ErrCode(0)
}

func (x *ChatApplyRsp) GetErrDesc() string {
	if x != nil {
		return x.ErrDesc
	}
	return ""
}

func (x *ChatApplyRsp) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ChatApplyRsp) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

// 用户取消
type ChatCancelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CalleeId int64 `protobuf:"varint,1,opt,name=calleeId,proto3" json:"calleeId,omitempty"` // 被邀请方id
}

func (x *ChatCancelReq) Reset() {
	*x = ChatCancelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCancelReq) ProtoMessage() {}

func (x *ChatCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCancelReq.ProtoReflect.Descriptor instead.
func (*ChatCancelReq) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{5}
}

func (x *ChatCancelReq) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

type ChatCancelRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode  pb_pub.ErrCode `protobuf:"varint,1,opt,name=errCode,proto3,enum=pb_pub.ErrCode" json:"errCode,omitempty"`
	ErrDesc  string         `protobuf:"bytes,2,opt,name=errDesc,proto3" json:"errDesc,omitempty"`
	CallerId int64          `protobuf:"varint,3,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId int64          `protobuf:"varint,4,opt,name=calleeId,proto3" json:"calleeId,omitempty"` // 必填
}

func (x *ChatCancelRsp) Reset() {
	*x = ChatCancelRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCancelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCancelRsp) ProtoMessage() {}

func (x *ChatCancelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCancelRsp.ProtoReflect.Descriptor instead.
func (*ChatCancelRsp) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{6}
}

func (x *ChatCancelRsp) GetErrCode() pb_pub.ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_pub.ErrCode(0)
}

func (x *ChatCancelRsp) GetErrDesc() string {
	if x != nil {
		return x.ErrDesc
	}
	return ""
}

func (x *ChatCancelRsp) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ChatCancelRsp) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

// 主播应答
type ChatAnswerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallerId int64       `protobuf:"varint,1,opt,name=callerId,proto3" json:"callerId,omitempty"`                               // 邀请方id
	Answer   CHAT_ANSWER `protobuf:"varint,2,opt,name=answer,proto3,enum=pb_msg_live_room.CHAT_ANSWER" json:"answer,omitempty"` // 同意还是拒绝
}

func (x *ChatAnswerReq) Reset() {
	*x = ChatAnswerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAnswerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAnswerReq) ProtoMessage() {}

func (x *ChatAnswerReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAnswerReq.ProtoReflect.Descriptor instead.
func (*ChatAnswerReq) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{7}
}

func (x *ChatAnswerReq) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ChatAnswerReq) GetAnswer() CHAT_ANSWER {
	if x != nil {
		return x.Answer
	}
	return CHAT_ANSWER_REFUSE
}

type ChatAnswerRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode  pb_pub.ErrCode `protobuf:"varint,1,opt,name=errCode,proto3,enum=pb_pub.ErrCode" json:"errCode,omitempty"`
	ErrDesc  string         `protobuf:"bytes,2,opt,name=errDesc,proto3" json:"errDesc,omitempty"`
	CallerId int64          `protobuf:"varint,3,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId int64          `protobuf:"varint,4,opt,name=calleeId,proto3" json:"calleeId,omitempty"` // 必填
}

func (x *ChatAnswerRsp) Reset() {
	*x = ChatAnswerRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAnswerRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAnswerRsp) ProtoMessage() {}

func (x *ChatAnswerRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAnswerRsp.ProtoReflect.Descriptor instead.
func (*ChatAnswerRsp) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{8}
}

func (x *ChatAnswerRsp) GetErrCode() pb_pub.ErrCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_pub.ErrCode(0)
}

func (x *ChatAnswerRsp) GetErrDesc() string {
	if x != nil {
		return x.ErrDesc
	}
	return ""
}

func (x *ChatAnswerRsp) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ChatAnswerRsp) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

// 用户关房
type ChatCloseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallerId int64 `protobuf:"varint,1,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId int64 `protobuf:"varint,2,opt,name=calleeId,proto3" json:"calleeId,omitempty"`
}

func (x *ChatCloseReq) Reset() {
	*x = ChatCloseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCloseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCloseReq) ProtoMessage() {}

func (x *ChatCloseReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCloseReq.ProtoReflect.Descriptor instead.
func (*ChatCloseReq) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{9}
}

func (x *ChatCloseReq) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ChatCloseReq) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

type ChatCloseRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChatCloseRsp) Reset() {
	*x = ChatCloseRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCloseRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCloseRsp) ProtoMessage() {}

func (x *ChatCloseRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCloseRsp.ProtoReflect.Descriptor instead.
func (*ChatCloseRsp) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{10}
}

// 用户关闭麦克风: 1. 同步到对方
type SetMicrophoneState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallerId int64 `protobuf:"varint,1,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId int64 `protobuf:"varint,2,opt,name=calleeId,proto3" json:"calleeId,omitempty"`
	State    int32 `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"` // 0 开 1 关
}

func (x *SetMicrophoneState) Reset() {
	*x = SetMicrophoneState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMicrophoneState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMicrophoneState) ProtoMessage() {}

func (x *SetMicrophoneState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMicrophoneState.ProtoReflect.Descriptor instead.
func (*SetMicrophoneState) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{11}
}

func (x *SetMicrophoneState) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *SetMicrophoneState) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

func (x *SetMicrophoneState) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// 设置暂离状态: 1. 同步给对方
type SetLeaveState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallerId int64 `protobuf:"varint,1,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId int64 `protobuf:"varint,2,opt,name=calleeId,proto3" json:"calleeId,omitempty"`
	State    int32 `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"` // 0:在线 1:暂离
}

func (x *SetLeaveState) Reset() {
	*x = SetLeaveState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLeaveState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLeaveState) ProtoMessage() {}

func (x *SetLeaveState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLeaveState.ProtoReflect.Descriptor instead.
func (*SetLeaveState) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{12}
}

func (x *SetLeaveState) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *SetLeaveState) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

func (x *SetLeaveState) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// 用户是否同意继续畅聊
type SetOneMore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallerId int64 `protobuf:"varint,1,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId int64 `protobuf:"varint,2,opt,name=calleeId,proto3" json:"calleeId,omitempty"`
	State    bool  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"` // 0: 到期结束 1:再来一场
}

func (x *SetOneMore) Reset() {
	*x = SetOneMore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOneMore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOneMore) ProtoMessage() {}

func (x *SetOneMore) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOneMore.ProtoReflect.Descriptor instead.
func (*SetOneMore) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{13}
}

func (x *SetOneMore) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *SetOneMore) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

func (x *SetOneMore) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

// 用户开启或关闭自动续费
type SetAutoRenewal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallerId int64 `protobuf:"varint,1,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId int64 `protobuf:"varint,2,opt,name=calleeId,proto3" json:"calleeId,omitempty"`
	State    bool  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"` // true:已开启 false:未开启
}

func (x *SetAutoRenewal) Reset() {
	*x = SetAutoRenewal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAutoRenewal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoRenewal) ProtoMessage() {}

func (x *SetAutoRenewal) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoRenewal.ProtoReflect.Descriptor instead.
func (*SetAutoRenewal) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{14}
}

func (x *SetAutoRenewal) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *SetAutoRenewal) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

func (x *SetAutoRenewal) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

// 小黑屋挂件状态,当前有几个小黑屋在畅聊,用户进房就推
type ChatCountChangeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ChatCountChangeNotify) Reset() {
	*x = ChatCountChangeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCountChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCountChangeNotify) ProtoMessage() {}

func (x *ChatCountChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCountChangeNotify.ProtoReflect.Descriptor instead.
func (*ChatCountChangeNotify) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{15}
}

func (x *ChatCountChangeNotify) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取小黑屋列表 1. 用户调起时去IM拉, 2. 在用户调起的情况下收到ChatCountChangeNotify后客户端再拉
type FetchChatRoomsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchChatRoomsReq) Reset() {
	*x = FetchChatRoomsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchChatRoomsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchChatRoomsReq) ProtoMessage() {}

func (x *FetchChatRoomsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchChatRoomsReq.ProtoReflect.Descriptor instead.
func (*FetchChatRoomsReq) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{16}
}

type FetchChatRoomsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*ChatRoomSummery `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *FetchChatRoomsRsp) Reset() {
	*x = FetchChatRoomsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchChatRoomsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchChatRoomsRsp) ProtoMessage() {}

func (x *FetchChatRoomsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchChatRoomsRsp.ProtoReflect.Descriptor instead.
func (*FetchChatRoomsRsp) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{17}
}

func (x *FetchChatRoomsRsp) GetRooms() []*ChatRoomSummery {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type ChatRoomSummery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallerId        int64  `protobuf:"varint,1,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId        int64  `protobuf:"varint,2,opt,name=calleeId,proto3" json:"calleeId,omitempty"`
	CallerUsername  string `protobuf:"bytes,3,opt,name=callerUsername,proto3" json:"callerUsername,omitempty"`
	CalleeUsername  string `protobuf:"bytes,4,opt,name=calleeUsername,proto3" json:"calleeUsername,omitempty"`
	CallerHeadimage string `protobuf:"bytes,5,opt,name=callerHeadimage,proto3" json:"callerHeadimage,omitempty"`
	Calleeheadimage string `protobuf:"bytes,6,opt,name=calleeheadimage,proto3" json:"calleeheadimage,omitempty"`
}

func (x *ChatRoomSummery) Reset() {
	*x = ChatRoomSummery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRoomSummery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomSummery) ProtoMessage() {}

func (x *ChatRoomSummery) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomSummery.ProtoReflect.Descriptor instead.
func (*ChatRoomSummery) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{18}
}

func (x *ChatRoomSummery) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ChatRoomSummery) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

func (x *ChatRoomSummery) GetCallerUsername() string {
	if x != nil {
		return x.CallerUsername
	}
	return ""
}

func (x *ChatRoomSummery) GetCalleeUsername() string {
	if x != nil {
		return x.CalleeUsername
	}
	return ""
}

func (x *ChatRoomSummery) GetCallerHeadimage() string {
	if x != nil {
		return x.CallerHeadimage
	}
	return ""
}

func (x *ChatRoomSummery) GetCalleeheadimage() string {
	if x != nil {
		return x.Calleeheadimage
	}
	return ""
}

// 被邀方同意,小黑屋建立
// 客户端收到此消息要给im发自动续费设置消息SetAutoRenewal
type ChatStartNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *ChatRoomInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ChatStartNotify) Reset() {
	*x = ChatStartNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatStartNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStartNotify) ProtoMessage() {}

func (x *ChatStartNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStartNotify.ProtoReflect.Descriptor instead.
func (*ChatStartNotify) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{19}
}

func (x *ChatStartNotify) GetInfo() *ChatRoomInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 发送到房间内所有人,用以触发小黑屋创建动画
type ChatCreateNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *ChatRoomSummery `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *ChatCreateNotify) Reset() {
	*x = ChatCreateNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCreateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCreateNotify) ProtoMessage() {}

func (x *ChatCreateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCreateNotify.ProtoReflect.Descriptor instead.
func (*ChatCreateNotify) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{20}
}

func (x *ChatCreateNotify) GetRoom() *ChatRoomSummery {
	if x != nil {
		return x.Room
	}
	return nil
}

// 房间自动续费或再聊一场 IM推送此消息更新房间到期时间
type DeadlineChangeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deadline int64 `protobuf:"varint,1,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (x *DeadlineChangeNotify) Reset() {
	*x = DeadlineChangeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadlineChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadlineChangeNotify) ProtoMessage() {}

func (x *DeadlineChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadlineChangeNotify.ProtoReflect.Descriptor instead.
func (*DeadlineChangeNotify) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{21}
}

func (x *DeadlineChangeNotify) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

// 小黑屋关闭
type ChatCloseNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallerId  int64           `protobuf:"varint,1,opt,name=callerId,proto3" json:"callerId,omitempty"`
	CalleeId  int64           `protobuf:"varint,2,opt,name=calleeId,proto3" json:"calleeId,omitempty"`
	CloseType CHAT_CLOSE_TYPE `protobuf:"varint,3,opt,name=closeType,proto3,enum=pb_msg_live_room.CHAT_CLOSE_TYPE" json:"closeType,omitempty"`
}

func (x *ChatCloseNotify) Reset() {
	*x = ChatCloseNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatCloseNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCloseNotify) ProtoMessage() {}

func (x *ChatCloseNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCloseNotify.ProtoReflect.Descriptor instead.
func (*ChatCloseNotify) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{22}
}

func (x *ChatCloseNotify) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ChatCloseNotify) GetCalleeId() int64 {
	if x != nil {
		return x.CalleeId
	}
	return 0
}

func (x *ChatCloseNotify) GetCloseType() CHAT_CLOSE_TYPE {
	if x != nil {
		return x.CloseType
	}
	return CHAT_CLOSE_TYPE_TIMEOUT
}

// 扣费成功,更新用户余额
type BalanceChangeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoinBalance int64 `protobuf:"varint,1,opt,name=coinBalance,proto3" json:"coinBalance,omitempty"`
}

func (x *BalanceChangeNotify) Reset() {
	*x = BalanceChangeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceChangeNotify) ProtoMessage() {}

func (x *BalanceChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceChangeNotify.ProtoReflect.Descriptor instead.
func (*BalanceChangeNotify) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{23}
}

func (x *BalanceChangeNotify) GetCoinBalance() int64 {
	if x != nil {
		return x.CoinBalance
	}
	return 0
}

// 派对房主持位没人,30秒后房间关闭
type HostCloseSoonNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HostCloseSoonNotify) Reset() {
	*x = HostCloseSoonNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostCloseSoonNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCloseSoonNotify) ProtoMessage() {}

func (x *HostCloseSoonNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCloseSoonNotify.ProtoReflect.Descriptor instead.
func (*HostCloseSoonNotify) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{24}
}

// 小黑屋礼物消息
type SecretGift struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId   int64     `protobuf:"varint,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ReceiverId int64     `protobuf:"varint,2,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	Gift       *LiveGift `protobuf:"bytes,3,opt,name=gift,proto3" json:"gift,omitempty"`
}

func (x *SecretGift) Reset() {
	*x = SecretGift{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretGift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretGift) ProtoMessage() {}

func (x *SecretGift) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_live_room_secret_room_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretGift.ProtoReflect.Descriptor instead.
func (*SecretGift) Descriptor() ([]byte, []int) {
	return file_pb_msg_live_room_secret_room_proto_rawDescGZIP(), []int{25}
}

func (x *SecretGift) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SecretGift) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SecretGift) GetGift() *LiveGift {
	if x != nil {
		return x.Gift
	}
	return nil
}

var File_pb_msg_live_room_secret_room_proto protoreflect.FileDescriptor

var file_pb_msg_live_room_secret_room_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69, 0x76,
	0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x1a, 0x20, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x6c,
	0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x70, 0x62, 0x5f, 0x70, 0x75, 0x62,
	0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x74, 0x65, 0x72, 0x12, 0x36, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x76, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x9c, 0x02, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f,
	0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x06, 0x63, 0x61, 0x6c,
	0x6c, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x6d,
	0x73, 0x67, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x43, 0x68, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x75,
	0x74, 0x6f, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x61, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x6f, 0x6e, 0x65, 0x4d, 0x6f, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6f,
	0x6e, 0x65, 0x4d, 0x6f, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0xb4, 0x01, 0x0a, 0x0c, 0x43, 0x68,
	0x61, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x8b, 0x01, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x73,
	0x70, 0x12, 0x29, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x5f, 0x70, 0x75, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x72, 0x72, 0x44, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x22, 0x2b,
	0x0a, 0x0d, 0x43, 0x68, 0x61, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x0d,
	0x43, 0x68, 0x61, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x29, 0x0a,
	0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x5f, 0x70, 0x75, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x44,
	0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x44, 0x65,
	0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x0d, 0x43, 0x68,
	0x61, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67,
	0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x43, 0x48, 0x41, 0x54, 0x5f,
	0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x8c,
	0x01, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x73, 0x70,
	0x12, 0x29, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x5f, 0x70, 0x75, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x72, 0x72, 0x44, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72,
	0x72, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x22, 0x46, 0x0a,
	0x0c, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c,
	0x6c, 0x65, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c,
	0x6c, 0x65, 0x65, 0x49, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x52, 0x73, 0x70, 0x22, 0x62, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x4d, 0x69, 0x63, 0x72,
	0x6f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65,
	0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5d, 0x0a, 0x0d, 0x53, 0x65, 0x74,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5a, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x4f,
	0x6e, 0x65, 0x4d, 0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x22, 0x5e, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x41, 0x75, 0x74, 0x6f, 0x52,
	0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x22, 0x2d, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x22, 0x4c, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x52, 0x73, 0x70, 0x12, 0x37, 0x0a,
	0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70,
	0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x79, 0x52,
	0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0xed, 0x01, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x61, 0x6c, 0x6c,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x68, 0x65, 0x61,
	0x64, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x45, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x32, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67,
	0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x49, 0x0a,
	0x10, 0x43, 0x68, 0x61, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x35, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x6d, 0x6d, 0x65,
	0x72, 0x79, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x32, 0x0a, 0x14, 0x44, 0x65, 0x61, 0x64,
	0x6c, 0x69, 0x6e, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x8a, 0x01, 0x0a,
	0x0f, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x09, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x70, 0x62,
	0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x43,
	0x48, 0x41, 0x54, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x09,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x13, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53,
	0x6f, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22, 0x78, 0x0a, 0x0a, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x47, 0x69, 0x66, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x67, 0x69, 0x66, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x47, 0x69, 0x66, 0x74, 0x52, 0x04, 0x67,
	0x69, 0x66, 0x74, 0x2a, 0x24, 0x0a, 0x0b, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x41, 0x4e, 0x53, 0x57,
	0x45, 0x52, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x46, 0x55, 0x53, 0x45, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x41, 0x47, 0x52, 0x45, 0x45, 0x10, 0x01, 0x2a, 0x37, 0x0a, 0x0f, 0x43, 0x48, 0x41,
	0x54, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0b, 0x0a, 0x07,
	0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x41, 0x4e,
	0x55, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x59, 0x5f, 0x48, 0x4f, 0x53, 0x54,
	0x10, 0x02, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x65, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x30, 0x30, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62,
	0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_msg_live_room_secret_room_proto_rawDescOnce sync.Once
	file_pb_msg_live_room_secret_room_proto_rawDescData = file_pb_msg_live_room_secret_room_proto_rawDesc
)

func file_pb_msg_live_room_secret_room_proto_rawDescGZIP() []byte {
	file_pb_msg_live_room_secret_room_proto_rawDescOnce.Do(func() {
		file_pb_msg_live_room_secret_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_msg_live_room_secret_room_proto_rawDescData)
	})
	return file_pb_msg_live_room_secret_room_proto_rawDescData
}

var file_pb_msg_live_room_secret_room_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_msg_live_room_secret_room_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_pb_msg_live_room_secret_room_proto_goTypes = []interface{}{
	(CHAT_ANSWER)(0),              // 0: pb_msg_live_room.CHAT_ANSWER
	(CHAT_CLOSE_TYPE)(0),          // 1: pb_msg_live_room.CHAT_CLOSE_TYPE
	(*Chatter)(nil),               // 2: pb_msg_live_room.Chatter
	(*ChatRoomInfo)(nil),          // 3: pb_msg_live_room.ChatRoomInfo
	(*UpdateChatPrice)(nil),       // 4: pb_msg_live_room.UpdateChatPrice
	(*ChatApplyReq)(nil),          // 5: pb_msg_live_room.ChatApplyReq
	(*ChatApplyRsp)(nil),          // 6: pb_msg_live_room.ChatApplyRsp
	(*ChatCancelReq)(nil),         // 7: pb_msg_live_room.ChatCancelReq
	(*ChatCancelRsp)(nil),         // 8: pb_msg_live_room.ChatCancelRsp
	(*ChatAnswerReq)(nil),         // 9: pb_msg_live_room.ChatAnswerReq
	(*ChatAnswerRsp)(nil),         // 10: pb_msg_live_room.ChatAnswerRsp
	(*ChatCloseReq)(nil),          // 11: pb_msg_live_room.ChatCloseReq
	(*ChatCloseRsp)(nil),          // 12: pb_msg_live_room.ChatCloseRsp
	(*SetMicrophoneState)(nil),    // 13: pb_msg_live_room.SetMicrophoneState
	(*SetLeaveState)(nil),         // 14: pb_msg_live_room.SetLeaveState
	(*SetOneMore)(nil),            // 15: pb_msg_live_room.SetOneMore
	(*SetAutoRenewal)(nil),        // 16: pb_msg_live_room.SetAutoRenewal
	(*ChatCountChangeNotify)(nil), // 17: pb_msg_live_room.ChatCountChangeNotify
	(*FetchChatRoomsReq)(nil),     // 18: pb_msg_live_room.FetchChatRoomsReq
	(*FetchChatRoomsRsp)(nil),     // 19: pb_msg_live_room.FetchChatRoomsRsp
	(*ChatRoomSummery)(nil),       // 20: pb_msg_live_room.ChatRoomSummery
	(*ChatStartNotify)(nil),       // 21: pb_msg_live_room.ChatStartNotify
	(*ChatCreateNotify)(nil),      // 22: pb_msg_live_room.ChatCreateNotify
	(*DeadlineChangeNotify)(nil),  // 23: pb_msg_live_room.DeadlineChangeNotify
	(*ChatCloseNotify)(nil),       // 24: pb_msg_live_room.ChatCloseNotify
	(*BalanceChangeNotify)(nil),   // 25: pb_msg_live_room.BalanceChangeNotify
	(*HostCloseSoonNotify)(nil),   // 26: pb_msg_live_room.HostCloseSoonNotify
	(*SecretGift)(nil),            // 27: pb_msg_live_room.SecretGift
	(*UserProp)(nil),              // 28: pb_msg_live_room.UserProp
	(pb_pub.ErrCode)(0),           // 29: pb_pub.ErrCode
	(*LiveGift)(nil),              // 30: pb_msg_live_room.LiveGift
}
var file_pb_msg_live_room_secret_room_proto_depIdxs = []int32{
	28, // 0: pb_msg_live_room.Chatter.userProp:type_name -> pb_msg_live_room.UserProp
	2,  // 1: pb_msg_live_room.ChatRoomInfo.caller:type_name -> pb_msg_live_room.Chatter
	2,  // 2: pb_msg_live_room.ChatRoomInfo.callee:type_name -> pb_msg_live_room.Chatter
	29, // 3: pb_msg_live_room.ChatApplyRsp.errCode:type_name -> pb_pub.ErrCode
	29, // 4: pb_msg_live_room.ChatCancelRsp.errCode:type_name -> pb_pub.ErrCode
	0,  // 5: pb_msg_live_room.ChatAnswerReq.answer:type_name -> pb_msg_live_room.CHAT_ANSWER
	29, // 6: pb_msg_live_room.ChatAnswerRsp.errCode:type_name -> pb_pub.ErrCode
	20, // 7: pb_msg_live_room.FetchChatRoomsRsp.rooms:type_name -> pb_msg_live_room.ChatRoomSummery
	3,  // 8: pb_msg_live_room.ChatStartNotify.info:type_name -> pb_msg_live_room.ChatRoomInfo
	20, // 9: pb_msg_live_room.ChatCreateNotify.room:type_name -> pb_msg_live_room.ChatRoomSummery
	1,  // 10: pb_msg_live_room.ChatCloseNotify.closeType:type_name -> pb_msg_live_room.CHAT_CLOSE_TYPE
	30, // 11: pb_msg_live_room.SecretGift.gift:type_name -> pb_msg_live_room.LiveGift
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pb_msg_live_room_secret_room_proto_init() }
func file_pb_msg_live_room_secret_room_proto_init() {
	if File_pb_msg_live_room_secret_room_proto != nil {
		return
	}
	file_pb_msg_live_room_live_room_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_msg_live_room_secret_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chatter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChatPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatApplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatApplyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCancelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCancelRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAnswerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAnswerRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCloseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCloseRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMicrophoneState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLeaveState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOneMore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAutoRenewal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCountChangeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchChatRoomsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchChatRoomsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRoomSummery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatStartNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCreateNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadlineChangeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatCloseNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceChangeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostCloseSoonNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_live_room_secret_room_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretGift); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_msg_live_room_secret_room_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_msg_live_room_secret_room_proto_goTypes,
		DependencyIndexes: file_pb_msg_live_room_secret_room_proto_depIdxs,
		EnumInfos:         file_pb_msg_live_room_secret_room_proto_enumTypes,
		MessageInfos:      file_pb_msg_live_room_secret_room_proto_msgTypes,
	}.Build()
	File_pb_msg_live_room_secret_room_proto = out.File
	file_pb_msg_live_room_secret_room_proto_rawDesc = nil
	file_pb_msg_live_room_secret_room_proto_goTypes = nil
	file_pb_msg_live_room_secret_room_proto_depIdxs = nil
}
