// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: pb_pub/version.proto

package pb_pub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Version im版本
type Version int32

const (
	Version_UnknownVersion Version = 0      // 位置版本
	Version_V210121        Version = 210121 // 椰趣接1v1通话版本
)

// Enum value maps for Version.
var (
	Version_name = map[int32]string{
		0:      "UnknownVersion",
		210121: "V210121",
	}
	Version_value = map[string]int32{
		"UnknownVersion": 0,
		"V210121":        210121,
	}
)

func (x Version) Enum() *Version {
	p := new(Version)
	*p = x
	return p
}

func (x Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Version) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_pub_version_proto_enumTypes[0].Descriptor()
}

func (Version) Type() protoreflect.EnumType {
	return &file_pb_pub_version_proto_enumTypes[0]
}

func (x Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Version.Descriptor instead.
func (Version) EnumDescriptor() ([]byte, []int) {
	return file_pb_pub_version_proto_rawDescGZIP(), []int{0}
}

var File_pb_pub_version_proto protoreflect.FileDescriptor

var file_pb_pub_version_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x5f, 0x70, 0x75, 0x62, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x62, 0x5f, 0x70, 0x75, 0x62, 0x2a, 0x2c,
	0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x07, 0x56, 0x32, 0x31, 0x30, 0x31, 0x32, 0x31, 0x10, 0xc9, 0xe9, 0x0c, 0x42, 0x20, 0x5a, 0x1e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x61, 0x6c, 0x6c,
	0x65, 0x65, 0x30, 0x30, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x70, 0x75, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_pub_version_proto_rawDescOnce sync.Once
	file_pb_pub_version_proto_rawDescData = file_pb_pub_version_proto_rawDesc
)

func file_pb_pub_version_proto_rawDescGZIP() []byte {
	file_pb_pub_version_proto_rawDescOnce.Do(func() {
		file_pb_pub_version_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_pub_version_proto_rawDescData)
	})
	return file_pb_pub_version_proto_rawDescData
}

var file_pb_pub_version_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_pub_version_proto_goTypes = []interface{}{
	(Version)(0), // 0: pb_pub.Version
}
var file_pb_pub_version_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_pub_version_proto_init() }
func file_pb_pub_version_proto_init() {
	if File_pb_pub_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_pub_version_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_pub_version_proto_goTypes,
		DependencyIndexes: file_pb_pub_version_proto_depIdxs,
		EnumInfos:         file_pb_pub_version_proto_enumTypes,
	}.Build()
	File_pb_pub_version_proto = out.File
	file_pb_pub_version_proto_rawDesc = nil
	file_pb_pub_version_proto_goTypes = nil
	file_pb_pub_version_proto_depIdxs = nil
}
