// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: pb_msg/msg_pusher/msgPusher.proto

package msg_pusher

import (
	pb_pub "github.com/leallee00/pb/pb_pub"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// topic:"t_msg_push_to_aim_user", channel: "c_msg_push_to_aim_user"
// 推送消息到特定用户
// jsStr={"srcUser":10001,"appList":[{"appName":"YEQU","aimUsers":[10295,16331]},{"appName":"YESE","aimUsers":[16123,15656]}],
//
//	"params":{"type":1,"roomId":10001,"nickname":"aaa","bigImageOriginal":"bbb"},
//	"title":"title","msg":"msg","exp":{"nkey1":"value1","nkey2":"value2"}}
//
// curl -d jsStr http://127.0.0.1:4151/pub?topic=t_msg_to_aim_user
type MsgPushToAimUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcUser int64             `protobuf:"varint,1,opt,name=srcUser,proto3" json:"srcUser,omitempty"` //发送方id
	AppList []*AppData        `protobuf:"bytes,2,rep,name=appList,proto3" json:"appList,omitempty"`
	Params  *Params           `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`                                                                                   //推送业务参数，json格式
	Title   string            `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                                                                                     //标题
	Msg     string            `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`                                                                                         //内容
	Exp     map[string]string `protobuf:"bytes,6,rep,name=exp,proto3" json:"exp,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 扩展参数
	Time    int64             `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`                                                                                      //时间
}

func (x *MsgPushToAimUser) Reset() {
	*x = MsgPushToAimUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPushToAimUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPushToAimUser) ProtoMessage() {}

func (x *MsgPushToAimUser) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPushToAimUser.ProtoReflect.Descriptor instead.
func (*MsgPushToAimUser) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_pusher_msgPusher_proto_rawDescGZIP(), []int{0}
}

func (x *MsgPushToAimUser) GetSrcUser() int64 {
	if x != nil {
		return x.SrcUser
	}
	return 0
}

func (x *MsgPushToAimUser) GetAppList() []*AppData {
	if x != nil {
		return x.AppList
	}
	return nil
}

func (x *MsgPushToAimUser) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *MsgPushToAimUser) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MsgPushToAimUser) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MsgPushToAimUser) GetExp() map[string]string {
	if x != nil {
		return x.Exp
	}
	return nil
}

func (x *MsgPushToAimUser) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type AppData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName  string  `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`           // 固定分配的客户端标识
	UserList []int64 `protobuf:"varint,2,rep,packed,name=userList,proto3" json:"userList,omitempty"` // 目标用户id列表
}

func (x *AppData) Reset() {
	*x = AppData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppData) ProtoMessage() {}

func (x *AppData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppData.ProtoReflect.Descriptor instead.
func (*AppData) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_pusher_msgPusher_proto_rawDescGZIP(), []int{1}
}

func (x *AppData) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppData) GetUserList() []int64 {
	if x != nil {
		return x.UserList
	}
	return nil
}

type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type             int32             `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`        //ios开播类型
	RoomId           int64             `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`    //开播房间id
	Nickname         string            `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"` //开播房间名称
	BigImageOriginal string            `protobuf:"bytes,4,opt,name=bigImageOriginal,proto3" json:"bigImageOriginal,omitempty"`
	Url              string            `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Exp              map[string]string `protobuf:"bytes,6,rep,name=exp,proto3" json:"exp,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 扩展参数
	GroupId          int64             `protobuf:"varint,7,opt,name=GroupId,proto3" json:"GroupId,omitempty"`                                                                                // 客服新增
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_pusher_msgPusher_proto_rawDescGZIP(), []int{2}
}

func (x *Params) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Params) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Params) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Params) GetBigImageOriginal() string {
	if x != nil {
		return x.BigImageOriginal
	}
	return ""
}

func (x *Params) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Params) GetExp() map[string]string {
	if x != nil {
		return x.Exp
	}
	return nil
}

func (x *Params) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// topic:"t_msg_push_to_all_user", channel: "c_msg_push_to_all_user"
// 推送消息到特定用户
// jsStr={"srcUser":10001,"params":{"type":1,"roomId":10001,"nickname":"aaa","bigImageOriginal":"bbb"},
//
//	"appName":"YEQUO","title":"title","msg":"msg","exp":{"nkey1":"value1","nkey2":"value2"}}
//
// curl -d jsStr http://127.0.0.1:4151/pub?topic=t_msg_to_all_user
type MsgPushToAllUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcUser int64             `protobuf:"varint,1,opt,name=srcUser,proto3" json:"srcUser,omitempty"`                                                                                //发送方id
	Params  *Params           `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`                                                                                   //推送业务参数，json格式
	AppName string            `protobuf:"bytes,3,opt,name=appName,proto3" json:"appName,omitempty"`                                                                                 //	固定分配的客户端标识
	Title   string            `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                                                                                     //标题
	Msg     string            `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`                                                                                         //内容
	Exp     map[string]string `protobuf:"bytes,6,rep,name=exp,proto3" json:"exp,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 扩展参数
}

func (x *MsgPushToAllUser) Reset() {
	*x = MsgPushToAllUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPushToAllUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPushToAllUser) ProtoMessage() {}

func (x *MsgPushToAllUser) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPushToAllUser.ProtoReflect.Descriptor instead.
func (*MsgPushToAllUser) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_pusher_msgPusher_proto_rawDescGZIP(), []int{3}
}

func (x *MsgPushToAllUser) GetSrcUser() int64 {
	if x != nil {
		return x.SrcUser
	}
	return 0
}

func (x *MsgPushToAllUser) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *MsgPushToAllUser) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *MsgPushToAllUser) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MsgPushToAllUser) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MsgPushToAllUser) GetExp() map[string]string {
	if x != nil {
		return x.Exp
	}
	return nil
}

// 推送回执
type PushReceiptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushId    int64  `protobuf:"varint,1,opt,name=pushId,proto3" json:"pushId,omitempty"`       // 推送id
	System    string `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`        // 系统
	IsReceive int32  `protobuf:"varint,3,opt,name=isReceive,proto3" json:"isReceive,omitempty"` // 是否收到 0=否，1=是
	IsOpen    int32  `protobuf:"varint,4,opt,name=isOpen,proto3" json:"isOpen,omitempty"`       // 是否打开 0=否，1=是
}

func (x *PushReceiptReq) Reset() {
	*x = PushReceiptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushReceiptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReceiptReq) ProtoMessage() {}

func (x *PushReceiptReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReceiptReq.ProtoReflect.Descriptor instead.
func (*PushReceiptReq) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_pusher_msgPusher_proto_rawDescGZIP(), []int{4}
}

func (x *PushReceiptReq) GetPushId() int64 {
	if x != nil {
		return x.PushId
	}
	return 0
}

func (x *PushReceiptReq) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *PushReceiptReq) GetIsReceive() int32 {
	if x != nil {
		return x.IsReceive
	}
	return 0
}

func (x *PushReceiptReq) GetIsOpen() int32 {
	if x != nil {
		return x.IsOpen
	}
	return 0
}

// 客户端推送token上报
type PushTokenSyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceCompany     pb_pub.MODEL_TYPE `protobuf:"varint,1,opt,name=DeviceCompany,proto3,enum=pb_pub.MODEL_TYPE" json:"DeviceCompany,omitempty"` // 设备厂商
	PushPlatformAppId string            `protobuf:"bytes,2,opt,name=PushPlatformAppId,proto3" json:"PushPlatformAppId,omitempty"`                 // 应用id，厂商开发者平台获取，每个包唯一
	Odid              string            `protobuf:"bytes,3,opt,name=Odid,proto3" json:"Odid,omitempty"`                                           // 开放设备标识符，开发者级别的非永久性设备标志符，同一设备上同一开发者的多个应用ODID取值相同，可用作设备唯一标识符
	Aaid              string            `protobuf:"bytes,4,opt,name=Aaid,proto3" json:"Aaid,omitempty"`                                           // 应用的匿名设备标识，标识运行在移动智能终端设备上的应用实例，同一开发者相同设备不同应用不同，用作实例唯一标识
	Token             string            `protobuf:"bytes,5,opt,name=Token,proto3" json:"Token,omitempty"`                                         // 推送token，每个实例都不同
	ExpiredAt         int64             `protobuf:"varint,6,opt,name=ExpiredAt,proto3" json:"ExpiredAt,omitempty"`                                // token失效时间，token失效必须重新获取，一般卸载重装或系统清理数据时失效
}

func (x *PushTokenSyncReq) Reset() {
	*x = PushTokenSyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushTokenSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTokenSyncReq) ProtoMessage() {}

func (x *PushTokenSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTokenSyncReq.ProtoReflect.Descriptor instead.
func (*PushTokenSyncReq) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_pusher_msgPusher_proto_rawDescGZIP(), []int{5}
}

func (x *PushTokenSyncReq) GetDeviceCompany() pb_pub.MODEL_TYPE {
	if x != nil {
		return x.DeviceCompany
	}
	return pb_pub.MODEL_TYPE(0)
}

func (x *PushTokenSyncReq) GetPushPlatformAppId() string {
	if x != nil {
		return x.PushPlatformAppId
	}
	return ""
}

func (x *PushTokenSyncReq) GetOdid() string {
	if x != nil {
		return x.Odid
	}
	return ""
}

func (x *PushTokenSyncReq) GetAaid() string {
	if x != nil {
		return x.Aaid
	}
	return ""
}

func (x *PushTokenSyncReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PushTokenSyncReq) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

var File_pb_msg_msg_pusher_msgPusher_proto protoreflect.FileDescriptor

var file_pb_msg_msg_pusher_msgPusher_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x70, 0x75, 0x73,
	0x68, 0x65, 0x72, 0x2f, 0x6d, 0x73, 0x67, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6d, 0x73, 0x67, 0x50,
	0x75, 0x73, 0x68, 0x65, 0x72, 0x1a, 0x11, 0x70, 0x62, 0x5f, 0x70, 0x75, 0x62, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc6, 0x02, 0x0a, 0x10, 0x4d, 0x73, 0x67,
	0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x41, 0x69, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x72, 0x63, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x73, 0x72, 0x63, 0x55, 0x73, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73,
	0x67, 0x5f, 0x6d, 0x73, 0x67, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x06,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6d, 0x73, 0x67, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x3d, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6d, 0x73, 0x67,
	0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x4d, 0x73, 0x67, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f,
	0x41, 0x69, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x78, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x3f, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x95, 0x02, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x62, 0x69, 0x67, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x62, 0x69, 0x67, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x33, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6d, 0x73, 0x67, 0x50, 0x75, 0x73,
	0x68, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x45, 0x78, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x78, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x97, 0x02, 0x0a, 0x10, 0x4d,
	0x73, 0x67, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x73, 0x72, 0x63, 0x55, 0x73, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x6d,
	0x73, 0x67, 0x5f, 0x6d, 0x73, 0x67, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x3d, 0x0a,
	0x03, 0x65, 0x78, 0x70, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x62, 0x5f,
	0x6d, 0x73, 0x67, 0x5f, 0x6d, 0x73, 0x67, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x4d, 0x73,
	0x67, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x45,
	0x78, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x65, 0x78, 0x70, 0x1a, 0x36, 0x0a, 0x08,
	0x45, 0x78, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x76, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x73, 0x68, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x75, 0x73, 0x68, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x73, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x22, 0xd6, 0x01, 0x0a,
	0x10, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65,
	0x71, 0x12, 0x38, 0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x70, 0x75,
	0x62, 0x2e, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0d, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x2c, 0x0a, 0x11, 0x50,
	0x75, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x70, 0x70, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x50, 0x75, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4f, 0x64, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4f, 0x64, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x41, 0x61, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x61, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x64, 0x41, 0x74, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x30, 0x30, 0x2f, 0x70, 0x62,
	0x2f, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x70, 0x75, 0x73, 0x68,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_msg_msg_pusher_msgPusher_proto_rawDescOnce sync.Once
	file_pb_msg_msg_pusher_msgPusher_proto_rawDescData = file_pb_msg_msg_pusher_msgPusher_proto_rawDesc
)

func file_pb_msg_msg_pusher_msgPusher_proto_rawDescGZIP() []byte {
	file_pb_msg_msg_pusher_msgPusher_proto_rawDescOnce.Do(func() {
		file_pb_msg_msg_pusher_msgPusher_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_msg_msg_pusher_msgPusher_proto_rawDescData)
	})
	return file_pb_msg_msg_pusher_msgPusher_proto_rawDescData
}

var file_pb_msg_msg_pusher_msgPusher_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_msg_msg_pusher_msgPusher_proto_goTypes = []interface{}{
	(*MsgPushToAimUser)(nil), // 0: pb_msg_msgPusher.MsgPushToAimUser
	(*AppData)(nil),          // 1: pb_msg_msgPusher.AppData
	(*Params)(nil),           // 2: pb_msg_msgPusher.Params
	(*MsgPushToAllUser)(nil), // 3: pb_msg_msgPusher.MsgPushToAllUser
	(*PushReceiptReq)(nil),   // 4: pb_msg_msgPusher.PushReceiptReq
	(*PushTokenSyncReq)(nil), // 5: pb_msg_msgPusher.PushTokenSyncReq
	nil,                      // 6: pb_msg_msgPusher.MsgPushToAimUser.ExpEntry
	nil,                      // 7: pb_msg_msgPusher.Params.ExpEntry
	nil,                      // 8: pb_msg_msgPusher.MsgPushToAllUser.ExpEntry
	(pb_pub.MODEL_TYPE)(0),   // 9: pb_pub.MODEL_TYPE
}
var file_pb_msg_msg_pusher_msgPusher_proto_depIdxs = []int32{
	1, // 0: pb_msg_msgPusher.MsgPushToAimUser.appList:type_name -> pb_msg_msgPusher.AppData
	2, // 1: pb_msg_msgPusher.MsgPushToAimUser.params:type_name -> pb_msg_msgPusher.Params
	6, // 2: pb_msg_msgPusher.MsgPushToAimUser.exp:type_name -> pb_msg_msgPusher.MsgPushToAimUser.ExpEntry
	7, // 3: pb_msg_msgPusher.Params.exp:type_name -> pb_msg_msgPusher.Params.ExpEntry
	2, // 4: pb_msg_msgPusher.MsgPushToAllUser.params:type_name -> pb_msg_msgPusher.Params
	8, // 5: pb_msg_msgPusher.MsgPushToAllUser.exp:type_name -> pb_msg_msgPusher.MsgPushToAllUser.ExpEntry
	9, // 6: pb_msg_msgPusher.PushTokenSyncReq.DeviceCompany:type_name -> pb_pub.MODEL_TYPE
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pb_msg_msg_pusher_msgPusher_proto_init() }
func file_pb_msg_msg_pusher_msgPusher_proto_init() {
	if File_pb_msg_msg_pusher_msgPusher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPushToAimUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPushToAllUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushReceiptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_pusher_msgPusher_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushTokenSyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_msg_msg_pusher_msgPusher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_msg_msg_pusher_msgPusher_proto_goTypes,
		DependencyIndexes: file_pb_msg_msg_pusher_msgPusher_proto_depIdxs,
		MessageInfos:      file_pb_msg_msg_pusher_msgPusher_proto_msgTypes,
	}.Build()
	File_pb_msg_msg_pusher_msgPusher_proto = out.File
	file_pb_msg_msg_pusher_msgPusher_proto_rawDesc = nil
	file_pb_msg_msg_pusher_msgPusher_proto_goTypes = nil
	file_pb_msg_msg_pusher_msgPusher_proto_depIdxs = nil
}
