// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: pb_msg/msg_sender/msgSender.proto

package msg_sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 私信推送
type MsgSenderNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcId            int64  `protobuf:"varint,1,opt,name=srcId,proto3" json:"srcId,omitempty"`                      //发送方ID
	Msg              string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                           //消息内容
	Title            string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                       //标题
	Type             int32  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                        //类型
	NickName         string `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`                 //发送方昵称
	BigImageOriginal string `protobuf:"bytes,6,opt,name=bigImageOriginal,proto3" json:"bigImageOriginal,omitempty"` //发送方头像
	GroupId          int64  `protobuf:"varint,7,opt,name=groupId,proto3" json:"groupId,omitempty"`                  // 客服消息新增
}

func (x *MsgSenderNotify) Reset() {
	*x = MsgSenderNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_sender_msgSender_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSenderNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSenderNotify) ProtoMessage() {}

func (x *MsgSenderNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_sender_msgSender_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSenderNotify.ProtoReflect.Descriptor instead.
func (*MsgSenderNotify) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_sender_msgSender_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSenderNotify) GetSrcId() int64 {
	if x != nil {
		return x.SrcId
	}
	return 0
}

func (x *MsgSenderNotify) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MsgSenderNotify) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MsgSenderNotify) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MsgSenderNotify) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *MsgSenderNotify) GetBigImageOriginal() string {
	if x != nil {
		return x.BigImageOriginal
	}
	return ""
}

func (x *MsgSenderNotify) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 成员变更通知
type ShopMemberChangeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId   int64 `protobuf:"varint,1,opt,name=shopId,proto3" json:"shopId,omitempty"`     // 商店id
	MemberID int64 `protobuf:"varint,2,opt,name=memberID,proto3" json:"memberID,omitempty"` // 新成员id
	Type     int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`         // 变更类型  1：新增  2：删除
}

func (x *ShopMemberChangeNotify) Reset() {
	*x = ShopMemberChangeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_msg_sender_msgSender_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopMemberChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopMemberChangeNotify) ProtoMessage() {}

func (x *ShopMemberChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_msg_sender_msgSender_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopMemberChangeNotify.ProtoReflect.Descriptor instead.
func (*ShopMemberChangeNotify) Descriptor() ([]byte, []int) {
	return file_pb_msg_msg_sender_msgSender_proto_rawDescGZIP(), []int{1}
}

func (x *ShopMemberChangeNotify) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ShopMemberChangeNotify) GetMemberID() int64 {
	if x != nil {
		return x.MemberID
	}
	return 0
}

func (x *ShopMemberChangeNotify) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_pb_msg_msg_sender_msgSender_proto protoreflect.FileDescriptor

var file_pb_msg_msg_sender_msgSender_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x2f, 0x6d, 0x73, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6d, 0x73, 0x67, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0xc5, 0x01, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x72, 0x63,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x72, 0x63, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x62, 0x69, 0x67, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x62, 0x69, 0x67, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x60, 0x0a,
	0x16, 0x53, 0x68, 0x6f, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42,
	0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65,
	0x61, 0x6c, 0x6c, 0x65, 0x65, 0x30, 0x30, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x6d, 0x73,
	0x67, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_msg_msg_sender_msgSender_proto_rawDescOnce sync.Once
	file_pb_msg_msg_sender_msgSender_proto_rawDescData = file_pb_msg_msg_sender_msgSender_proto_rawDesc
)

func file_pb_msg_msg_sender_msgSender_proto_rawDescGZIP() []byte {
	file_pb_msg_msg_sender_msgSender_proto_rawDescOnce.Do(func() {
		file_pb_msg_msg_sender_msgSender_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_msg_msg_sender_msgSender_proto_rawDescData)
	})
	return file_pb_msg_msg_sender_msgSender_proto_rawDescData
}

var file_pb_msg_msg_sender_msgSender_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_msg_msg_sender_msgSender_proto_goTypes = []interface{}{
	(*MsgSenderNotify)(nil),        // 0: pb_msg_msgSender.MsgSenderNotify
	(*ShopMemberChangeNotify)(nil), // 1: pb_msg_msgSender.ShopMemberChangeNotify
}
var file_pb_msg_msg_sender_msgSender_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_msg_msg_sender_msgSender_proto_init() }
func file_pb_msg_msg_sender_msgSender_proto_init() {
	if File_pb_msg_msg_sender_msgSender_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_msg_msg_sender_msgSender_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSenderNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_msg_msg_sender_msgSender_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopMemberChangeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_msg_msg_sender_msgSender_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_msg_msg_sender_msgSender_proto_goTypes,
		DependencyIndexes: file_pb_msg_msg_sender_msgSender_proto_depIdxs,
		MessageInfos:      file_pb_msg_msg_sender_msgSender_proto_msgTypes,
	}.Build()
	File_pb_msg_msg_sender_msgSender_proto = out.File
	file_pb_msg_msg_sender_msgSender_proto_rawDesc = nil
	file_pb_msg_msg_sender_msgSender_proto_goTypes = nil
	file_pb_msg_msg_sender_msgSender_proto_depIdxs = nil
}
