final Map<String, String> smileys = <String, String>{
  'Grinning Face': '😀',
  'Grinning Face With Big Eyes': '😃',
  'Grinning Face With Smiling Eyes': '😄',
  'Beaming Face With Smiling Eyes': '😁',
  'Grinning Squinting Face': '😆',
  'Grinning Face With Sweat': '😅',
  'Rolling on the Floor Laughing': '🤣',
  'Face With Tears of Joy': '😂',
  'Slightly Smiling Face': '🙂',
  'Upside-Down Face': '🙃',
  'Winking Face': '😉',
  'Smiling Face With Smiling Eyes': '😊',
  'Smiling Face With Halo': '😇',
  'Smiling Face With Hearts': '🥰',
  'Smiling Face With Heart-Eyes': '😍',
  'Star-Struck': '🤩',
  'Face Blowing a Kiss': '😘',
  'Kissing Face': '😗',
  'Smiling Face': '☺️',
  'Kissing Face With Closed Eyes': '😚',
  'Kissing Face With Smiling Eyes': '😙',
  'Face Savoring Food': '😋',
  'Face With Tongue': '😛',
  'Winking Face With Tongue': '😜',
  'Zany Face': '🤪',
  'Squinting Face With Tongue': '😝',
  'Money-Mouth Face': '🤑',
  'Hugging Face': '🤗',
  'Face With Hand Over Mouth': '🤭',
  'Shushing Face': '🤫',
  'Thinking Face': '🤔',
  'Zipper-Mouth Face': '🤐',
  'Face With Raised Eyebrow': '🤨',
  'Neutral Face': '😐',
  'Expressionless Face': '😑',
  'Face Without Mouth': '😶',
  'Smirking Face': '😏',
  'Unamused Face': '😒',
  'Face With Rolling Eyes': '🙄',
  'Grimacing Face': '😬',
  'Lying Face': '🤥',
  'Relieved Face': '😌',
  'Pensive Face': '😔',
  'Sleepy Face': '😪',
  'Drooling Face': '🤤',
  'Sleeping Face': '😴',
  'Face With Medical Mask': '😷',
  'Face With Thermometer': '🤒',
  'Face With Head-Bandage': '🤕',
  'Nauseated Face': '🤢',
  'Face Vomiting': '🤮',
  'Sneezing Face': '🤧',
  'Hot Face': '🥵',
  'Cold Face': '🥶',
  'Woozy Face': '🥴',
  'Dizzy Face': '😵',
  'Exploding Head': '🤯',
  'Cowboy Hat Face': '🤠',
  'Partying Face': '🥳',
  'Smiling Face With Sunglasses': '😎',
  'Nerd Face': '🤓',
  'Face With Monocle': '🧐',
  'Confused Face': '😕',
  'Worried Face': '😟',
  'Slightly Frowning Face': '🙁',
  'Frowning Face': '☹️',
  'Face With Open Mouth': '😮',
  'Hushed Face': '😯',
  'Astonished Face': '😲',
  'Flushed Face': '😳',
  'Pleading Face': '🥺',
  'Frowning Face With Open Mouth': '😦',
  'Anguished Face': '😧',
  'Fearful Face': '😨',
  'Anxious Face With Sweat': '😰',
  'Sad but Relieved Face': '😥',
  'Crying Face': '😢',
  'Loudly Crying Face': '😭',
  'Face Screaming in Fear': '😱',
  'Confounded Face': '😖',
  'Persevering Face': '😣',
  'Disappointed Face': '😞',
  'Downcast Face With Sweat': '😓',
  'Weary Face': '😩',
  'Tired Face': '😫',
  'Yawning Face': '🥱',
  'Face With Steam From Nose': '😤',
  'Pouting Face': '😡',
  'Angry Face': '😠',
  'Waving Hand': '👋',
  'Raised Back of Hand': '🤚',
  'Hand With Fingers Splayed': '🖐️',
  'Raised Hand': '✋',
  'Vulcan Salute': '🖖',
  'OK Hand': '👌',
  'Victory Hand': '✌️',
  'Crossed Fingers': '🤞',
  'Love-You Gesture': '🤟',
  'Sign of the Horns': '🤘',
  'Call Me Hand': '🤙',
  'Backhand Index Pointing Left': '👈',
  'Backhand Index Pointing Right': '👉',
  'Backhand Index Pointing Up': '👆',
  'Middle Finger': '🖕',
  'Backhand Index Pointing Down': '👇',
  'Index Pointing Up': '☝️',
  'Thumbs Up': '👍',
  'Thumbs Down': '👎',
  'Raised Fist': '✊',
  'Oncoming Fist': '👊',
  'Left-Facing Fist': '🤛',
  'Right-Facing Fist': '🤜',
  'Clapping Hands': '👏',
  'Raising Hands': '🙌',
  'Open Hands': '👐',
  'Palms Up Together': '🤲',
  'Handshake': '🤝',
  'Folded Hands': '🙏',
  'Flexed Biceps': '💪',
  'Kiss Mark': '💋',
  'Red Heart': '❤️',
  'Broken Heart': '💔',
  'Dizzy': '💫',
  'Sweat Droplets': '💦',
  'Dashing Away': '💨',
  'Bomb': '💣',
  'Hundred Points': '💯',
  'Zzz': '💤',
};
